# Generated by Django 5.1.1 on 2024-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availibility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
