# Generated by Django 5.1.1 on 2024-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_product_alter_discountcode_name_and_more'),
        ('product', '0004_alter_product_availibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='product.product'),
        ),
    ]
